version: "3.7"
services:
  nginx:
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    volumes:
      - ./thz-ms/public:/var/www/thz-ms/public
    working_dir: /var/www/thz-ms/public
    links:
      - php
    ports:
      - "8001:80"
  php:
    build: ./docker/php
    volumes:
      - ./thz-ms:/var/www/thz-ms
    working_dir: /var/www/thz-ms
    command: php-fpm
    links:
      - db
      - redis
    environment:
      PHP_OPCACHE_ENABLE: 1
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 0
  db:
    build: ./docker/postgres
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: thz
      POSTGRES_USER: thz
      POSTGRES_PASSWORD: secret
  redis:
    build: ./docker/redis
    volumes:
      - ./.redis:/data
    ports:
      - "6380:6379"
