version: "3.8"
services:
  nginx:
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    volumes:
      - ./thz-ms/public:/var/www/thz-ms/public
    working_dir: /var/www/thz-ms/public
    links:
      - php
    ports:
      - 8001:80
  php:
    build: ./docker/php
    volumes:
      - ./thz-ms:/var/www/thz-ms
    working_dir: /var/www/thz-ms
    command: php-fpm
    links:
      - db
      - redis
    environment:
      PHP_OPCACHE_ENABLE: 1
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 0
  db:
    image: postgres:13.0-alpine
    restart: unless-stopped
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: thz
      POSTGRES_USER: thz
      POSTGRES_PASSWORD: secret
  redis:
    image: redis:6.0-alpine
    restart: unless-stopped
    volumes:
      - ./docker/redis/redis.conf:/etc/redis.conf
      - ./.redis:/data:delegated
